#!/bin/bash

version=$(git describe --tags --always)
if [[ $1 != "" ]]
then
    version=$1
fi

# shellcheck disable=SC2209
SED=sed
if [[ "$OSTYPE" == "darwin"* ]]
then
    if ! which gsed&> /dev/null
    then
        printf "gsed is required for MacOS\n"
        exit 1
    fi
    SED=gsed
fi

# shellcheck disable=SC2016
searchstring=$(printf 'SCRIPTVERSION="local-dev"')
replstring=$(printf 'SCRIPTVERSION="%s"' "$version")
sedcmd=$(printf "s/%s/%s/" "$searchstring" "$replstring")
$SED -i "$sedcmd" ./gvm