#!/bin/bash

version=$(git describe --tags --always)
if [[ $1 != "" ]]
then
    version=$1
fi

# shellcheck disable=SC2016
searchstring=$(printf 'SCRIPTVERSION="$(git describe --tags --always)"')
replstring=$(printf 'SCRIPTVERSION="%s"' "$version")
sedcmd=$(printf "s/%s/%s/" "$searchstring" "$replstring")
gsed -i "$sedcmd" ./gvm